### ISSUE TITLE
No async task available error

### ISSUE THREAD

**Issue by trevorturk** [socketry/async-job-adapter-active_job#9]
I tested `async-job` in production, and things mostly look great, except I do see a (very small) number of exceptions bubbling up in Sentry. I'm not sure what the cause might be, but I'll think about it some more, and please do let me know if you have any ideas. The number of exceptions is quite small, so I'm having trouble thinking of why `bin/rails` is being invoked...?

![Screenshot 2024-08-13 at 3 43 23 PM](https://github.com/user-attachments/assets/73c32cbe-96d0-44e2-b482-ce34433c6921)

I'm switching back to my previous setup for now, but it's very easy for me to toggle between them since https://github.com/socketry/async-job-adapter-active_job/issues/3 has been fixed -- thank you!

**Comment by ioquatix** [comment]
Are you able to give me a full stack trace?

**Comment by ioquatix** [comment]
I released v0.14.1 which might fix this. Maybe you have a cron job scheduling jobs?

**Comment by trevorturk** [comment]
Ah, that must be it -- I have a cron job running every minute that performs a job.

I updated to the latest, but now when I run my tests I get the following:

```
/Users/trevorturk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/minitest-5.25.0/lib/minitest.rb:457:in `with_info_handler': wrong number of arguments (given 1, expected 2) (ArgumentError)
	from /Users/trevorturk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelization/worker.rb:49:in `perform_job'
	from /Users/trevorturk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelization/worker.rb:38:in `work_from_queue'
	from /Users/trevorturk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelization/worker.rb:27:in `block in start'
	from /Users/trevorturk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelization/worker.rb:15:in `fork'
	from /Users/trevorturk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelization/worker.rb:15:in `start'
	from /Users/trevorturk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelization.rb:37:in `block in start'
	from <internal:numeric>:237:in `times'
	from /Users/trevorturk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelization.rb:36:in `each'
	from /Users/trevorturk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelization.rb:36:in `map'
	from /Users/trevorturk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelization.rb:36:in `start'
	from /Users/trevorturk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelize_executor.rb:19:in `start'
	from /Users/trevorturk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/minitest-5.25.0/lib/minitest.rb:284:in `run'
	from /Users/trevorturk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/minitest-5.25.0/lib/minitest.rb:85:in `block in autorun'
```

One per `parallelize` call in my `test_helper.rb`:

```
class ActiveSupport::TestCase
  MAX_PARALLEL_WORKERS = 15 # max number of Redis dbs we have allocated for testing
  parallelize workers: MAX_PARALLEL_WORKERS # FIXME GitHub CI (and local) fails if set to 1
```

I wonder if anything jumps out at you, or I'd be happy to try to work up a minimal sample Rails app to try to repro?

**Comment by trevorturk** [comment]
Ok, all looks good here! I'm running `async-job` w/ the `Inline` adapter in production, will be processing ~500k jobs/day!
